### ISSUE TITLE
When this will be available on nuget?

### ISSUE THREAD

**Issue by arivera12** [willem640/Geolocation.Blazor#1]
I searched other repos and I found that they don't work or not backward compatible but yours seems the must completed and backward compatible.

I downloaded this project and included it on a solution and its working properly.

I can help you publishing this repo as a nuget package.

Please let me know if you want and/or need my help on this.

**Comment by willem640** [comment]
I'm flattered! I feel like some parts of the project are a bit hacky (the part with the disposables), but I'll put it on NuGet anyway (once I have time) as it isn't that bad

**Comment by willem640** [comment]
I finally got to it, it should be validated within an hour

**Comment by arivera12** [comment]
thanks you so much!
